<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Odemehub</RootNamespace>
    <AssemblyName>Odemehub.Sdk</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>

    <PackageId>Odemehub.Sdk</PackageId>
    <Version>1.0.1</Version>
    <Description>ödemehub ödeme geçidi için .NET istemcisi.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/odemehub/dotnet-sdk</PackageProjectUrl>
    <RepositoryUrl>https://github.com/odemehub/dotnet-sdk.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
